### ISSUE TITLE
Restamp only specific pages

### ISSUE THREAD

**Issue by panuhorsmalahti** [TimvdLippe/iron-lazy-pages#31]
It would be useful if we could specify which pages to always restamp and which not.

**Comment by TimvdLippe** [comment]
It should be as easy as modifying [this line](https://github.com/TimvdLippe/iron-lazy-pages/blob/master/iron-lazy-page.html#L126) to `restamp || this.restamp` and adding the property `restamp` to `iron-lazy-page`. Could you submit a PR with that? :smile:

**Comment by nicholaswmin** [comment]
Guessing that `master` has changed  since the above was posted - Is [this the line][1] you're talking about? - I can submit that PR 💯 


[1]: https://github.com/TimvdLippe/iron-lazy-pages/blob/master/iron-lazy-page.html#L136

**Comment by TimvdLippe** [comment]
Yes, but templates and restamping will be removed in 2.0 sadly. See #44

**Comment by nicholaswmin** [comment]
Yikes - that's a shame.

It's not quite clear in #44 as to why they are being removed. 

Is it because they are not supported in all major browsers?

> First of all type extension is not supported by all major browsers.
> It is therefore not possible to rely on `template is="..."` extensions.

Is it because it's more clean and lean to not use templates at all?

> Secondly, upgrading from iron-pages to iron-lazy-pages was quite intrusive
and the template syntax was confusing to users.


If the 1st point is the case then perhaps the Polymer team can shed some light as to why it's not working cross-browser. If the 2nd point is the case then it's a shame to ditch such a major performance enhancement just for the sake of ergonomics.

I'm pushing this because I've seen major performance improvements when restamping. It allows navigating through complex DOM chunks whilst still keeping performance high - which feels very "native-y"

**Comment by TimvdLippe** [comment]
@nicholaswmin Thanks for the feedback! Could you provide me two timelines: 1. using the current 2.0-preview wihout restamping and 2. the 1.0 version with restamping. I would be very interested in seeing the flamecharts of both actions when navigating between pages. You can upload the data as a gist here on GitHub. Please check out https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/timeline-tool#save_and_load_recordings on how to export the data from the dev tools.

Once again thank you and I am very open to improvements with templates, if we can have data proving the performance gains of restamping.

**Comment by nicholaswmin** [comment]
@TimvdLippe  you got me there.

> I'm pushing this because I've seen major performance improvements when restamping

I haven't run any benchmarks at all and the flamecharts won't support so much my case as it is now - I'll call this a white lie and try to get away with it.

It's really about scalability that I'm interested in. I'd like to know that I can keep adding stuff to my DOM and still be careless about it since I can just restamp pages if and when needed.

There's still valid points about this:

- It would prevent accidental JS interaction with hidden pages
- It "resets" the state of the page.

I'm pretty sure there's already a marginal improvement in performance, in certain areas in my use case, when restamping. 

I'll go on and create some flamecharts anyway

**Comment by TimvdLippe** [comment]
@nicholaswmin No problem, even if you later find a usecase that does justify template do not hesitate to post it here!

> It's really about scalability that I'm interested in. I'd like to know that I can keep adding stuff to my DOM and still be careless about it since I can just restamp pages if and when needed.

To my knowledge, using CSS to show/hide elements is a lot faster than recreating the DOM tree multiple times. Maybe we should ask in the Polymer Slack whether this claim is true. Now the implication of using CSS is that the state is maintained even when the element is hidden. This is something the user of the element should be aware of and is different behavior than in 1.0.

**Comment by TimvdLippe** [comment]
On a different note, my current thinking is supporting `dom-if` as possible sub-page, but it might have some limitations compared to the previous implementation.

**Comment by nicholaswmin** [comment]
> To my knowledge, using CSS to show/hide elements is a lot faster than recreating the DOM tree multiple times

That's true when you have a flat tree of hierarchies in terms of iron-pages.

If an iron-page contains multiple levels of nested iron-pages, `restamp` should allow much faster switching of the parent iron-page, since it won't need to re-render all the subpages.

This is still just speculation from my end - I just want to get my use-case across

**Comment by nicholaswmin** [comment]
So, theoretically here's a use case:

- A top level iron-page containing 10 subpages.
- Each subpage contains a subpages.
- For brevity, let's assume that each sub page of either level takes ~50ms to render.

First rendering the component that contains all these `iron-pages` would need 10 x 4 x 50ms = 2000ms.
Things could get messier as more and more levels are added.

With `restamp`, it would take 100ms since it stamps only 1 page out of each level. 

Sure, `restamp`-ing is going to make navigation a bit clunkier. I'd take it that it's a matter of balance between first render time of the whole component, and smoothness when navigating between pages.

The restamping option would, again theoretically, work wonders if you have many sub-levels with small DOM chunks in each sublevel page. `restamp` wouldn't create a smoothness issue when navigating and first-render and/or navigating through higher levels wouldn't naively re-render all the lower-level DOM chunks.


### Notes:

- I'm using the word *render* equivalent to CSS display/hide.
- I'm using the word *restamp* equivalent to DOM creation/destruction.

**Comment by web-padawan** [comment]
`restamp` can be useful when you have to re-run some `iron-ajax` requests each time the DOM is recreated.

**Comment by TimvdLippe** [comment]
@nicholaswmin You should be lazy-loading the element definitions instead. Therefore you only pay 1 x 4 x 50ms per page navigation if it is the first time you are navigating to that page. See `data-path` in the 2.0-preview and `path` on `iron-lazy-page` in 1.0.

@web-padawan Yes exactly I do think that is a valid usecase, therefore I am considering to include `<dom-if>` compatibility

**Comment by jpradelle** [comment]
Restamp is also a nice way to do grabage collection of dom elements.

**Comment by TimvdLippe** [comment]
This has been fixed per #48
